name: Scan for Vulnerabilities

on: push

jobs:
  osv-scan:
    name: Run OSV Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OSV-Scanner binary
        run: |
          sudo wget -O /usr/bin/osv-scanner https://github.com/google/osv-scanner/releases/download/v1.4.0/osv-scanner_1.4.0_linux_amd64 && sudo chmod +x /usr/bin/osv-scanner

      - name: Scan requirements.txt and save result
        run: |
          osv-scanner --lockfile=requirements.txt --format=json > vul_results.json

      - name: Upload vulnerability report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: osv-vulnerability-report
          path: vul_results.json
        if: always() 

  oast-snyk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master      
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"

      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Install Node modules
        run: npm install

      - name: Run Snyk
        run: snyk test --strict-out-of-sync=false --json . > snyk-results.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: Snyk               
          path: snyk-results.json
        if: always()     
        
        
  odc-backend:
    runs-on: ubuntu-20.04
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'webgoat'
          path: '.'
          format: 'JSON'

      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports   
        if: always()  # what is this for?

        
