name: Scan for Vulnerabilities

on: push

jobs:
  osv-scan:
    name: Run OSV Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OSV-Scanner binary
        run: |
          sudo wget -O /usr/bin/osv-scanner https://github.com/google/osv-scanner/releases/download/v1.4.0/osv-scanner_1.4.0_linux_amd64 && sudo chmod +x /usr/bin/osv-scanner

      - name: Scan requirements.txt and save result
        run: |
          osv-scanner --lockfile=requirements.txt --format=json > vul_results.json

      - name: Upload vulnerability report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: osv-vulnerability-report
          path: vul_results.json
